export default {
    arrowBack: require('./arrow-back.png'),
    comment: require('./comment.png'),
    first_banner: require('./first_banner.jpg'),
    profile: require('./profile.png'),
    second_banner: require('./second_banner.jpg'),
    third_banner: require('./third_banner.jpg'),
    imageButton: require('./imageButton.png'),
    category: require('./category.png'),
    homeItem1: require('./homeItem1.png'),
    homeItem2: require('./homeItem2.png'),
    homeItem3: require('./homeItem3.png'),
    home_invite: require('./home_invite.png'),
    groupCardImage: require('./groupCardImage.png'),
    eventDetails: require('./eventDetails.png'),
    eventUser: require('./eventUser.png'),
    eventGallery: require('./eventGallery.png'),
    profile_cover: require('./profile_cover.png'),
}